# AppVeyor configuration file.
version: '1.9.0.{build}'

# Build worker image (VM template)
image:
  - Visual Studio 2015
  - Ubuntu

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# clone directory
clone_folder: c:\projects\rom-properties

# Don't build if source files aren't modified.
only_commits:
  files:
    - appveyor.yml
    - '**/CMakeLists.txt'
    - '**/*.cmd'
    - '**/*.sh'
    - extlib/**/*
    - src/**/*

environment:
  matrix:
    - image: Visual Studio 2015
      platform: x86
      configuration: Debug
      compiler: msvc2015

    #- image: Visual Studio 2015
    #  platform: x86
    #  configuration: Release
    #  compiler: msvc2015

    #- image: Visual Studio 2015
    #  platform: x64
    #  configuration: Debug
    #  compiler: msvc2015

    #- image: Visual Studio 2015
    #  platform: x64
    #  configuration: Release
    #  compiler: msvc2015

    # NOTE: This one stays disabled after finishing Ubuntu testing.
    #- image: Visual Studio 2015
    #  platform: x86
    #  configuration: Debug
    #  compiler: mingw-w64

    #- image: Visual Studio 2015
    #  platform: x64
    #  configuration: Debug
    #  compiler: mingw-w64

    - image: Ubuntu
      platform: x64
      configuration: Release

# Run CMake with optional features turned off initially.
before_build:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%
  - cmd: appveyor.cmd OFF
  - sh: cd ${APPVEYOR_BUILD_FOLDER}
  - sh: sudo ./appveyor-dpkg.sh
  - sh: ./appveyor.sh OFF

# Build once with optional features turned off,
# then build again with optional features turned on.
build_script:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%\build
  - cmd: cmake --build . --config %configuration%
  - cmd: cd ..
  - cmd: appveyor.cmd ON
  - cmd: cd %APPVEYOR_BUILD_FOLDER%\build
  - cmd: cmake --build . --config %configuration%
  - sh: cd ${APPVEYOR_BUILD_FOLDER}/build
  - sh: cmake --build . --config ${configuration}
  - sh: cd ..
  - sh: ./appveyor.sh ON
  - sh: cd ${APPVEYOR_BUILD_FOLDER}/build
  - sh: cmake --build . --config ${configuration}

test_script:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%\build
  - cmd: ctest -V -C %configuration%
  - sh: cd ${APPVEYOR_BUILD_FOLDER}/build
  - sh: ctest -V -C ${configuration}

after_test:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%\build
  - cmd: ..\appveyor-artifacts.cmd
